MvcCoreUtilidades/ViewComponents/MenuCochesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreUtilidades.Models;
using MvcCoreUtilidades.Repositories;

namespace MvcCoreUtilidades.ViewComponents
{
    public class MenuCochesViewComponent: ViewComponent
    {
        private RepositoryCoches repo;
        public MenuCochesViewComponent(RepositoryCoches repo)
        {
            this.repo = repo;
        }

        //PODRIAMOS TENER TODOS LOS METODOS QUE DESEEMOS.
        //ES OBLIGATORIO TENER EL METODO InvokeAsync con task
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Coche> coches = this.repo.GetCoches();
            return View(coches);
        }
    }
}

MvcCoreUtilidades/Views/Shared/Components/MenuCoches/Default.cshtml
@model List<Coche>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Mi Menú</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                
                @foreach(Coche car in Model){
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">@car.Marca</a>
                    </li>
                    @await Component.InvokeAsync("MenuCoches")
                    <li class=""></li>
                }
            </ul>
        </div>
    </div>
</nav>